# Generated by Django 3.1.5 on 2021-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='quota',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='mobile_number',
            field=models.CharField(max_length=200),
        ),
    ]
