# Generated by Django 3.1.5 on 2021-01-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210122_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=200)),
                ('quota', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TajweedReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=200)),
                ('quota', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='MyModel',
            new_name='EgazatReg',
        ),
    ]
